/**
 * Phase 5 — Seed SQL generator.
 *
 * Reads the canonical Persian editorial sources under src/lib/data/ and
 * emits the seed migration consumed by Supabase. Re-run whenever the
 * editorial sources are updated.
 *
 *   bun run scripts/generate-phase5-seed.ts
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { MASTER_PRODUCTS } from "../src/lib/data/products-master";
import { MASTER_CATEGORY_COPY } from "../src/lib/data/category-copy";
import { COMPANY_PROFILE } from "../src/lib/data/company";

const __dirname = dirname(fileURLToPath(import.meta.url));

const SLUG_TO_ENUM: Record<string, string> = {
  "power-wheelchairs": "POWER_WHEELCHAIRS",
  "manual-wheelchairs": "MANUAL_WHEELCHAIRS",
  "mobility-aids": "MOBILITY_AIDS",
  "shower-wheelchairs": "MOBILITY_AIDS",
  "patient-lifts": "MOBILITY_AIDS",
  "mobility-scooters": "MOBILITY_AIDS",
  accessories: "ACCESSORIES",
  "spare-parts": "SPARE_PARTS",
};

// PostgreSQL string literal escape.
const sql = (v: string) => `'${v.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) =>
  v === null || v === undefined ? "NULL" : `${sql(JSON.stringify(v))}::jsonb`;
const fa = (s: string | undefined | null) => (s ? { fa: s } : null);

const lines: string[] = [];
const push = (s: string) => lines.push(s);

push("-- ============================================================================");
push("-- Phase 5 — Seed Data");
push("-- Generated by scripts/generate-phase5-seed.ts from src/lib/data/*.ts");
push("-- Idempotent: safe to re-run.");
push("-- ============================================================================");
push("");
push("BEGIN;");
push("");

// ----------------------------------------------------------------------------
// company_profile (single row)
// ----------------------------------------------------------------------------
const company = {
  name: { fa: COMPANY_PROFILE.nameFa, en: COMPANY_PROFILE.nameEn },
  mission: fa(COMPANY_PROFILE.mission),
  vision: fa(COMPANY_PROFILE.vision),
  history: fa(COMPANY_PROFILE.history),
  certificates: [
    ...(COMPANY_PROFILE.certificates.businessLicense
      ? [{ name: COMPANY_PROFILE.certificates.businessLicense }]
      : []),
    ...(COMPANY_PROFILE.certificates.manufacturingLicense
      ? [{ name: COMPANY_PROFILE.certificates.manufacturingLicense }]
      : []),
    ...COMPANY_PROFILE.certificates.standards.map((s) => ({ name: s })),
  ],
  contact: {
    phones: [
      ...COMPANY_PROFILE.contact.phoneNumbers,
      COMPANY_PROFILE.contact.mobileWhatsapp,
    ],
    emails: [...COMPANY_PROFILE.contact.emails],
    address: { fa: COMPANY_PROFILE.contact.headOfficeAddress },
    social: { ...COMPANY_PROFILE.contact.social },
  },
};

push("-- company_profile (single row)");
push(`INSERT INTO public.company_profile (id, name, mission, vision, history, certificates, contact)`);
push(`VALUES ('default', ${jsonb(company.name)}, ${jsonb(company.mission)}, ${jsonb(company.vision)}, ${jsonb(company.history)}, ${jsonb(company.certificates)}, ${jsonb(company.contact)})`);
push(`ON CONFLICT (id) DO UPDATE SET`);
push(`  name = EXCLUDED.name, mission = EXCLUDED.mission, vision = EXCLUDED.vision,`);
push(`  history = EXCLUDED.history, certificates = EXCLUDED.certificates, contact = EXCLUDED.contact;`);
push("");

// ----------------------------------------------------------------------------
// category_copy (one row per legacy slug; FK to enum)
// ----------------------------------------------------------------------------
push("-- category_copy");
for (const c of MASTER_CATEGORY_COPY) {
  const enumKey = SLUG_TO_ENUM[c.key];
  if (!enumKey) continue;
  push(
    `INSERT INTO public.category_copy (slug, category_key, title, short_description, full_description, usage, target_audience) VALUES (`,
  );
  push(`  ${sql(c.key)}, '${enumKey}'::public.product_category_key,`);
  push(`  ${jsonb({ fa: c.fa.title })},`);
  push(`  ${jsonb({ fa: c.fa.shortDescription })},`);
  push(`  ${jsonb({ fa: c.fa.fullDescription })},`);
  push(`  ${jsonb({ fa: c.fa.usage })},`);
  push(`  ${jsonb({ fa: c.fa.targetAudience })}`);
  push(`) ON CONFLICT (slug) DO UPDATE SET`);
  push(`  category_key = EXCLUDED.category_key,`);
  push(`  title = EXCLUDED.title,`);
  push(`  short_description = EXCLUDED.short_description,`);
  push(`  full_description = EXCLUDED.full_description,`);
  push(`  usage = EXCLUDED.usage,`);
  push(`  target_audience = EXCLUDED.target_audience;`);
}
push("");

// ----------------------------------------------------------------------------
// products + spec groups/items + certifications + faq items
// ----------------------------------------------------------------------------
push("-- products");
for (const p of MASTER_PRODUCTS) {
  const enumKey = SLUG_TO_ENUM[p.category];
  if (!enumKey) {
    push(`-- skipped (unknown category): ${p.slug}`);
    continue;
  }
  const status =
    p.status === "published" ? "PUBLISHED" : p.status === "archived" ? "ARCHIVED" : "DRAFT";
  const productId = `seed:${p.slug}`; // deterministic id for idempotency

  const name = p.fa.name ?? p.nameEn;
  const series = p.seriesEn ? { fa: p.seriesEn, en: p.seriesEn } : null;
  const description = fa(p.fa.description);
  const shortDescription = fa(p.fa.shortDescription);
  const features = p.fa.features.map((f) => ({ fa: f }));

  push(`INSERT INTO public.products (id, slug, category_key, code, name, series, description, short_description, features, status)`);
  push(`VALUES (`);
  push(`  ${sql(productId)},`);
  push(`  ${sql(p.slug)},`);
  push(`  '${enumKey}'::public.product_category_key,`);
  push(`  ${p.fa.brand ? sql(p.fa.brand + "-" + p.slug) : "NULL"},`);
  push(`  ${sql(name)},`);
  push(`  ${jsonb(series)},`);
  push(`  ${jsonb(description)},`);
  push(`  ${jsonb(shortDescription)},`);
  push(`  ${jsonb(features)},`);
  push(`  '${status}'::public.product_status`);
  push(`) ON CONFLICT (slug) DO UPDATE SET`);
  push(`  category_key = EXCLUDED.category_key,`);
  push(`  code = EXCLUDED.code,`);
  push(`  name = EXCLUDED.name,`);
  push(`  series = EXCLUDED.series,`);
  push(`  description = EXCLUDED.description,`);
  push(`  short_description = EXCLUDED.short_description,`);
  push(`  features = EXCLUDED.features,`);
  push(`  status = EXCLUDED.status;`);

  // Replace child rows for idempotency.
  push(`DELETE FROM public.specification_groups WHERE product_id = (SELECT id FROM public.products WHERE slug = ${sql(p.slug)});`);
  push(`DELETE FROM public.certifications      WHERE product_id = (SELECT id FROM public.products WHERE slug = ${sql(p.slug)});`);
  push(`DELETE FROM public.faq_items           WHERE product_id = (SELECT id FROM public.products WHERE slug = ${sql(p.slug)});`);

  if (p.specs.length > 0) {
    const groupId = `seed:${p.slug}:technical`;
    push(`INSERT INTO public.specification_groups (id, product_id, key, label, position) VALUES (`);
    push(`  ${sql(groupId)},`);
    push(`  (SELECT id FROM public.products WHERE slug = ${sql(p.slug)}),`);
    push(`  'technical',`);
    push(`  ${jsonb({ fa: "مشخصات فنی", en: "Technical Specifications" })},`);
    push(`  0`);
    push(`);`);
    p.specs.forEach((s, idx) => {
      const itemId = `seed:${p.slug}:technical:${s.key}`;
      push(`INSERT INTO public.specification_items (id, group_id, key, label, value, position) VALUES (`);
      push(`  ${sql(itemId)},`);
      push(`  ${sql(groupId)},`);
      push(`  ${sql(s.key)},`);
      push(`  ${jsonb({ fa: s.labelFa, en: s.labelEn })},`);
      push(`  ${jsonb({ fa: s.valueFa })},`);
      push(`  ${idx}`);
      push(`);`);
    });
  }

  p.certifications.forEach((c, idx) => {
    push(`INSERT INTO public.certifications (id, product_id, name, position) VALUES (`);
    push(`  ${sql(`seed:${p.slug}:cert:${idx}`)},`);
    push(`  (SELECT id FROM public.products WHERE slug = ${sql(p.slug)}),`);
    push(`  ${sql(c.name)},`);
    push(`  ${idx}`);
    push(`);`);
  });

  const faqs: { q: { fa: string }; a: { fa: string } }[] = [];
  if (p.fa.warrantyPeriod) {
    faqs.push({
      q: { fa: "مدت گارانتی چقدر است؟" },
      a: {
        fa: p.fa.warrantyConditions
          ? `${p.fa.warrantyPeriod} — ${p.fa.warrantyConditions}`
          : p.fa.warrantyPeriod,
      },
    });
  }
  if (p.fa.afterSales) {
    faqs.push({ q: { fa: "خدمات پس از فروش چگونه است؟" }, a: { fa: p.fa.afterSales } });
  }
  faqs.forEach((f, idx) => {
    push(`INSERT INTO public.faq_items (id, product_id, question, answer, position) VALUES (`);
    push(`  ${sql(`seed:${p.slug}:faq:${idx}`)},`);
    push(`  (SELECT id FROM public.products WHERE slug = ${sql(p.slug)}),`);
    push(`  ${jsonb(f.q)},`);
    push(`  ${jsonb(f.a)},`);
    push(`  ${idx}`);
    push(`);`);
  });
  push("");
}

// ----------------------------------------------------------------------------
// migration_log
// ----------------------------------------------------------------------------
push("-- migration_log");
push(`INSERT INTO public.migration_log (id, status, batch_name, total_records, processed_records, notes) VALUES (`);
push(`  'phase5-seed-' || to_char(now(), 'YYYYMMDDHH24MISS'),`);
push(`  'completed', 'phase5_seed_data',`);
push(`  ${MASTER_PRODUCTS.length + MASTER_CATEGORY_COPY.length + 1},`);
push(`  ${MASTER_PRODUCTS.length + MASTER_CATEGORY_COPY.length + 1},`);
push(`  'Phase 5 — Data Import (products + categories + company profile)'`);
push(`);`);
push("");
push("COMMIT;");

const out = resolve(__dirname, "./generated/phase5_seed_data.sql");
writeFileSync(out, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${out} (${lines.length} lines)`);
